- hosts: all
  become: yes
  tasks:
    - name: Install BIND DNS Server
      apt:
        name: bind9
        state: present

    - name: Deploy named.conf.options
      template:
        src: templates/named.conf.options.j2
        dest: /etc/bind/named.conf.options
      notify: restart bind9

    - name: Deploy named.conf.local
      template:
        src: templates/named.conf.local.j2
        dest: /etc/bind/named.conf.local
      notify: restart bind9

    - name: Configure DNS Zone for Site 1
      template:
        src: templates/db.site1.j2
        dest: /etc/bind/db.site1
      when: inventory_hostname in groups['site1']
      notify: restart bind9

    - name: Configure DNS Zone for Site 2
      template:
        src: templates/db.site2.j2
        dest: /etc/bind/db.site2
      when: inventory_hostname in groups['site2']
      notify: restart bind9

  handlers:
    - name: restart bind9
      service:
        name: bind9
        state: restarted

