---
- name: Ajouter les entrées users
- hosts: ldap_server
  become: yes
  tasks:

    - name: Copier et ajouter les fichiers LDIF pour les utilisateurs et l>#
      copy:
        src: "templates/{{ item }}"
        dest: "/tmp/{{ item }}"

        - name: Ajouter les entrées ldif
          command: ldapadd -x -D "cn=admin,dc=istycorp,dc=fr" -w "{{ ldap_>#          when: "item not in ldap_data.stdout"
          loop:
            - user1.ldif
            - user2.ldif
            - user3.ldif
            - user4.ldif
